server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Bakugan03
    url: jdbc:postgresql://localhost:5432/first_work_db_2

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://auth-server:9000