package com.example.first_work_project.service;

import com.example.first_work_project.controller.KnowledgeBaseCurrentVersionController;

public interface KnowledgeBaseCurrentVersionService extends GeneralService<KnowledgeBaseCurrentVersionController>{
}
